name: Auto Version Bump

on:
  push:
    branches: [ main ]
  # Only run on pushes to main, not on PR creation/updates

jobs:
  version-bump:
    runs-on: ubuntu-latest
    # Add explicit permissions to fix 403 error
    permissions:
      contents: write  # Required to push changes and create tags
      actions: read    # Required to read actions
    # Only run if the push is not from the version bump commit itself
    if: "!contains(github.event.head_commit.message, 'chore: bump version')"
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        # Use a PAT to allow the action to trigger other workflows
        token: ${{ secrets.GITHUB_TOKEN }}
        fetch-depth: 0
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Configure git
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
    
    - name: Bump version
      run: |
        # Get current version
        CURRENT_VERSION=$(node -p "require('./package.json').version")
        echo "Current version: $CURRENT_VERSION"
        
        # Bump patch version
        npm version patch --no-git-tag-version
        
        # Get new version
        NEW_VERSION=$(node -p "require('./package.json').version")
        echo "New version: $NEW_VERSION"
        
        # Commit the version bump
        git add package.json package-lock.json
        git commit -m "chore: bump version to $NEW_VERSION"
        
        # Push the changes
        git push origin main
        
        # Create and push a git tag
        git tag "v$NEW_VERSION"
        git push origin "v$NEW_VERSION"
        
        echo "Version bumped from $CURRENT_VERSION to $NEW_VERSION"